baseURL = "https://flashlight-workshop.github.io"
languageCode = "en-gb"
title = "FLASHLIGHT"
defaultContentLanguage = "en"
theme = "cupper"

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
description = "First Workshop on Formal Methods In High-Level Synthesis."
homeMetaContent = "First Workshop on Formal Methods In High-Level Synthesis."
footer = "Organised by John Wickerson and Lana Josipović."
dateFormat = "Jan 2, 2006"
codePenUser = "someUser"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = false
defaultDarkTheme = false
moveFooterToHeader = true
logoAlt = "First Workshop on Formal Methods In High-Level Synthesis."
customCss = [ "css/custom_01.css" ]
customJs = [ ]

[[menu.nav]]
name = "About"
url = "/"
weight = 1

[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

[markup.highlight]
codeFences = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[markup.tableOfContents]
endLevel = 6
startLevel = 2
